# central role for shared dongle topology
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_PROFILE_COUNT=5
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=6

# display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
CONFIG_ZMK_IDLE_TIMEOUT=60000
CONFIG_BT_BAS=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
