## Default configuration for the Prospector Extension.
# Prospector builds combine with *_dongle shields that default ZMK display off.
CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y
CONFIG_LVGL=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_SSD1306=n
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_Z_BITS_PER_PIXEL=16

CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=y
# CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=50
# CONFIG_PROSPECTOR_PROSPECTOR_ROTATE_DISPLAY_180=n
# CONFIG_PROSPECTOR_LAYER_ROLLER_ALL_CAPS=n

# ## Prospector New Status Screens
# Use one of the following to enable a new status screen. Only one can be enabled at a time.
# CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
# CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# ## Prospector New Status Screens - Additional Options
# CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=n
# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=y
# CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=50
# CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=y
# CONFIG_PROSPECTOR_SHOW_MODIFIERS=y
# CONFIG_PROSPECTOR_SHOW_INACTIVE_MODIFIERS=y
# CONFIG_PROSPECTOR_MODIFIER_ORDER="GACS"
# CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=70
# CONFIG_PROSPECTOR_ANIMATION_INTENSITY_DECAY_SEC=30
# CONFIG_PROSPECTOR_ANIMATION_FLOW_DECAY_SEC=300

# ## Yet Another Dongle Screen(YADS)
# CONFIG_DONGLE_SCREEN_HORIZONTAL=y
# CONFIG_DONGLE_SCREEN_FLIPPED=n
# CONFIG_DONGLE_SCREEN_SYSTEM_ICON=0
# CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=y
# CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT_EVALUATION_INTERVAL_MS=1000
# CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT_MIN_RAW_VALUE=0
# CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT_MAX_RAW_VALUE=100
# CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=300
# CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=90
# CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=10
# CONFIG_DONGLE_SCREEN_DEFAULT_BRIGHTNESS=30
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_MODIFIER=0
# CONFIG_DONGLE_SCREEN_TOGGLE_KEYCODE=113
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_UP_KEYCODE=115
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_DOWN_KEYCODE=114
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=10
# CONFIG_DONGLE_SCREEN_WPM_ACTIVE=y
# CONFIG_DONGLE_SCREEN_MODIFIER_ACTIVE=y
# CONFIG_DONGLE_SCREEN_LAYER_ACTIVE=y
# CONFIG_DONGLE_SCREEN_OUTPUT_ACTIVE=y
# CONFIG_DONGLE_SCREEN_BATTERY_ACTIVE=y
# CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT_TEST=n
