# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Disable Eyelash Corne-half specific hardware options for dongle target.
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
CONFIG_BT_BAS=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
