# OLED display
CONFIG_ZMK_DISPLAY=y

# custom status screen (nice-view-gem)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# turn off gem animation to save battery
CONFIG_NICE_VIEW_GEM_ANIMATION=n
# CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
