## ZDD central configuration
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
CONFIG_BT_BAS=n

## ZMK DONGLE DISPLAY
# CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
# CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y
# CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="left"    # default, or "center", "right"
# CONFIG_ZMK_DONGLE_DISPLAY_LAYER_NAME_SCROLL_WIDTH=50  # default is 50 pixels
# CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="right"
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
# CONFIG_ZMK_DONGLE_DISPLAY_WPM_DISABLED_LAYERS="layers" # comma separated
# CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
# CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=n
# CONFIG_ZMK_DONGLE_DISPLAY_LAYER=n
# CONFIG_LV_Z_VDB_SIZE=32
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
