# DEBUG OPTIONS
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
CONFIG_ZMK_USB_LOGGING=n

# Enable ZMK Studio support
CONFIG_ZMK_STUDIO=y

# Bluetooth tweaks
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Tune bluetooth profiles for quick select (default 5)
# CONFIG_BT_MAX_CONN=3

# "Eager Debouncing"
# Trying to lower the input lag.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Set sleep timeout to 30min (30*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# External power
CONFIG_ZMK_EXT_POWER=y
# Disable external power when not connected to USB
# CONFIG_ZMK_EXT_POWER_USB_ONLY=y

# Enable SPI per keyboard/board only (avoid enabling SPI on targets with no SPI driver usage)
# CONFIG_SPI=y

# soft-off
CONFIG_ZMK_PM_SOFT_OFF=y

# battery reporting
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# mouse emulation
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
# enable F13-F24
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y

# OLED display
# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Widget settings
# CONFIG_ZMK_WIDGET_WPM_STATUS=n
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# CONFIG_ZMK_WIDGET_LAYER_STATUS=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
# CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# RDP compatibility.
# CONFIG_ZMK_HID_SEPARATE_MOD_RELEASE_REPORT=y


# Enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Backlight
# CONFIG_ZMK_BACKLIGHT=y
# CONFIG_ZMK_BACKLIGHT_BRT_START=100
# CONFIG_ZMK_BACKLIGHT_ON_START=y
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=n

# RGB underglow (WS2812 chain)
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=90
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# LED Indicator
# CONFIG_RGBLED_WIDGET=y

# zmk-rgbled-widget configs
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y
# CONFIG_RGBLED_WIDGET_LAYER_COLOR=4
