name: Build All Firmware

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: build-all-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

