name: Run tests (main)

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build.yml"
      - ".github/workflows/build-all.yml"
      - ".github/workflows/build-inputs.yml"
      - ".github/workflows/release.yml"
      - ".github/workflows/test-main.yml"
      - ".github/workflows/test-release.yml"
      - "build.yaml"
      - "boards/**"
      - "config/**"
      - "config/west.yml"
      - "dts/**"
      - "include/**"
      - "src/**"
      - "tests/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - ".github/workflows/build-all.yml"
      - ".github/workflows/build-inputs.yml"
      - ".github/workflows/release.yml"
      - ".github/workflows/test-main.yml"
      - ".github/workflows/test-release.yml"
      - "build.yaml"
      - "boards/**"
      - "config/**"
      - "config/west.yml"
      - "dts/**"
      - "include/**"
      - "src/**"
      - "tests/**"
  schedule:
    - cron: "0 21 * * 3"

concurrency:
  group: test-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: urob/zmk-actions/.github/workflows/run-tests.yml@main
    with:
      toolchain: gnuarmemb
      zmk-version: main
