name: Check for new ZMK releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 3" # Run weekly on Wednesday at 22:00 UTC

permissions:
  contents: write

concurrency:
  group: upgrade-zmk
  cancel-in-progress: true

jobs:
  upgrade-zmk:
    uses: urob/zmk-actions/.github/workflows/upgrade-zmk.yml@main
    secrets:
      # PAT requires write access to pull requests
      token: ${{ secrets.ZMK_ACTIONS_TOKEN }}
